export const AUTH_SERVICE = 'AUTH_SERVICE';
export const CART_SERVICE = 'CART_SERVICE';
export const PRODUCT_SERVICE = 'PRODUCT_SERVICE';
export const ORDERS_SERVICE = 'ORDERS_SERVICE';
export const IMAGES_SERVICE = 'IMAGES_SERVICE';
